/**
 * 카카오 API 관련 상수
 */

// 카카오 API 타임아웃 (10초)
const KAKAO_API_TIMEOUT = 10000;

// 카카오 API 재시도 지연 시간 (1.5초)
const KAKAO_API_RETRY_DELAY = 1500;

// 카카오 API 최대 재시도 횟수
const KAKAO_API_MAX_RETRIES = 2;

// HTTP 상태 코드
const HTTP_STATUS_UNAUTHORIZED = 401;
const HTTP_STATUS_FORBIDDEN = 403;

// 에러 코드
const ERROR_CODE_KAKAO_API_FAILED = "KAKAO_API_FAILED";
const ERROR_CODE_KAKAO_API_TIMEOUT = "KAKAO_API_TIMEOUT";

module.exports = {
  KAKAO_API_TIMEOUT,
  KAKAO_API_RETRY_DELAY,
  KAKAO_API_MAX_RETRIES,
  HTTP_STATUS_UNAUTHORIZED,
  HTTP_STATUS_FORBIDDEN,
  ERROR_CODE_KAKAO_API_FAILED,
  ERROR_CODE_KAKAO_API_TIMEOUT,
};

