const USER_MISSIONS_COLLECTION = "userMissions";
const USER_MISSION_STATS_COLLECTION = "userMissionStats";
const MISSION_POSTS_COLLECTION = "missionPosts";

const MISSION_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  QUIT: "QUIT",
};

const BLOCKED_STATUSES = [MISSION_STATUS.IN_PROGRESS, MISSION_STATUS.COMPLETED];

const MAX_ACTIVE_MISSIONS = 3;

module.exports = {
  USER_MISSIONS_COLLECTION,
  USER_MISSION_STATS_COLLECTION,
  MISSION_POSTS_COLLECTION,
  MISSION_STATUS,
  BLOCKED_STATUSES,
  MAX_ACTIVE_MISSIONS,
};

