module.exports = {
  DEFAULT_MISSION_PAGE_SIZE: 20,
  MAX_MISSION_PAGE_SIZE: 50,
  NOTION_MAX_PAGE_SIZE: 100,
  DEFAULT_POST_PAGE_SIZE: 20,
  MAX_POST_PAGE_SIZE: 50,
  DEFAULT_COMMENT_PAGE_SIZE: 10,
  MAX_COMMENT_PAGE_SIZE: 20,
};

