export const LINK_URL = {
  ROOT: "/",
  HOME: "/home",
  LOGIN: "/login",
  KAKAO_LOGIN: "/kakao-login",
  EMAIL_LOGIN: "/email-login",
  TERMS_OF_SERVICE: "/terms-of-service",
  PRIVACY_POLICY: "/privacy-policy",
  FIND_PASSWORD: "/find-password",
  EMAIL_SIGNUP: "/signup/email",
  MISSION: "/mission",
  COMMUNITY: "/community",
  COMMUNITY_POST: "/community/post",
  DOWNLOAD: "/download",
  ROUTINES: "/routines",
  ROUTINES_APPLY: "/routines/[id]/apply",
  MY_PAGE: "/my-page",
  MY_PAGE_EDIT: "/my-page/edit",
  SETTINGS: "/settings",
  PERSONAL_INFO: "/settings/personal-info",
} as const;
