export const LINK_URL = {
  ROOT: "/",
  HOME: "/home",
  LOGIN: "/login",
  KAKAO_LOGIN: "/kakao-login",
  EMAIL_LOGIN: "/email-login",
  TERMS_OF_SERVICE:
    "https://www.notion.so/youthvoice/2a845f524cd0805bb753d8b98694ff3d",
  PRIVACY_POLICY:
    "https://www.notion.so/youthvoice/2a845f524cd080278624e57498305bf2",
  FIND_PASSWORD: "/find-password",
  EMAIL_SIGNUP: "/signup/email",
  MISSION: "/mission",
  MISSION_LIST: "/mission/list",
  MISSION_CERTIFY: "/mission/certify",
  COMMUNITY: "/community",
  COMMUNITY_POST: "/community/post",
  COMMUNITY_WRITE: "/community/write",
  DOWNLOAD: "/download",
  ROUTINES: "/routines",
  ROUTINES_APPLY: "/routines/[id]/apply",
  MY_PAGE: "/my-page",
  MY_PAGE_EDIT: "/my-page/edit",
  SETTINGS: "/settings",
  PERSONAL_INFO: "/settings/personal-info",
  ANNOUNCEMENTS: "/announcements",
} as const;
