export const LINK_URL = {
  ROOT: "/",
  HOME: "/home",
  LOGIN: "/login",
  KAKAO_LOGIN: "/kakao-login",
  EMAIL_LOGIN: "/email-login",
  TERMS_OF_SERVICE: "/terms-of-service",
  PRIVACY_POLICY: "/privacy-policy",
  FIND_PASSWORD: "/find-password",
  EMAIL_SIGNUP: "/signup/email",
  MISSION: "/mission",
  COMMUNITY: "/community",
  DOWNLOAD: "/download",
  ROUTINES: "/routines",
  MY_PAGE: "/my-page",
  MY_PAGE_EDIT: "/my-page/edit",
  MYPAGE_SETTING_LEAVE: "/mypage-setting-leave",
} as const;
